version: '3.8'

services:
  web_service:
    image: company_profile:1.0.0
    ports:
      - target: 8080
        published: 10610
        mode: ingress
    environment:
      - ./source/storage/:/var/www/html/storage/
    # Limit default logging container
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
        mode: non-blocking
  nginx:
      image: nginx:alpine
      container_name: laravel-nginx
      restart: unless-stopped
      ports:
        - "8000:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./:/var/www/html
      depends_on:
        - app